-- Da de alta partidas presupuestales para los 24 tipos de gasto activos en
-- cfg.tipos_gasto que no tenían ninguna partida propia (auditoría 2026-08-21:
-- caían todos al catch-all de cada área, incluidos 14 con OPs reales ya
-- capturadas sin desglose propio en Comparativo/Flujo/Dashboard).
--
-- Alcance confirmado con el usuario:
--   - 21 tipos de gasto de uso general (nómina, impuestos, insumos,
--     licencias, servicios, etc.) → una partida por cada uno de los 6
--     módulos con Centro de Costo (Golf, Mantenimiento, Hípico, Polo,
--     Eventos, Patron's), en el área operativa principal de cada módulo.
--     Locales queda fuera (sin Centro de Costo, solo ingresos).
--   - Alimento para Caballos / Medicamentos e Insumos Veterinarios → solo
--     Hípico, área Caballerizas (25) en vez del área operativa general,
--     por ser gasto de establo, no administrativo.
--   - Catering → solo Eventos.
--
-- CC/Área por módulo (confirmados contra cfg.centros_costo/cfg.areas):
--   Golf CC2/Área39, Mantenimiento CC1/Área21, Hípico CC3/Área40,
--   Polo CC4/Área41, Eventos CC7/Área45, Patron's CC5/Área42.

BEGIN;

INSERT INTO ctrl.ppto_partidas
  (nombre, tipo, id_centro_costo_fk, id_area_fk, orden, activo, fuente_real, tipo_gasto, modulo, incluir_presupuesto, incluir_flujo)
VALUES
  ('Nómina Quincenal [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Nómina Quincenal', 'Golf', true, true),
  ('Nómina Quincenal [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Nómina Quincenal', 'Mantenimiento', true, true),
  ('Nómina Quincenal [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Nómina Quincenal', 'Hípico', true, true),
  ('Nómina Quincenal [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Nómina Quincenal', 'Polo', true, true),
  ('Nómina Quincenal [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Nómina Quincenal', 'Eventos', true, true),
  ('Nómina Quincenal [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Nómina Quincenal', 'Patron''s', true, true),
  ('IMSS [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'IMSS', 'Golf', true, true),
  ('IMSS [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'IMSS', 'Mantenimiento', true, true),
  ('IMSS [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'IMSS', 'Hípico', true, true),
  ('IMSS [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'IMSS', 'Polo', true, true),
  ('IMSS [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'IMSS', 'Eventos', true, true),
  ('IMSS [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'IMSS', 'Patron''s', true, true),
  ('ISR [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'ISR', 'Golf', true, true),
  ('ISR [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'ISR', 'Mantenimiento', true, true),
  ('ISR [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'ISR', 'Hípico', true, true),
  ('ISR [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'ISR', 'Polo', true, true),
  ('ISR [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'ISR', 'Eventos', true, true),
  ('ISR [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'ISR', 'Patron''s', true, true),
  ('I.V.A [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'I.V.A', 'Golf', true, true),
  ('I.V.A [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'I.V.A', 'Mantenimiento', true, true),
  ('I.V.A [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'I.V.A', 'Hípico', true, true),
  ('I.V.A [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'I.V.A', 'Polo', true, true),
  ('I.V.A [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'I.V.A', 'Eventos', true, true),
  ('I.V.A [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'I.V.A', 'Patron''s', true, true),
  ('PTU [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'PTU', 'Golf', true, true),
  ('PTU [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'PTU', 'Mantenimiento', true, true),
  ('PTU [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'PTU', 'Hípico', true, true),
  ('PTU [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'PTU', 'Polo', true, true),
  ('PTU [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'PTU', 'Eventos', true, true),
  ('PTU [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'PTU', 'Patron''s', true, true),
  ('Fonacot [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Fonacot', 'Golf', true, true),
  ('Fonacot [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Fonacot', 'Mantenimiento', true, true),
  ('Fonacot [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Fonacot', 'Hípico', true, true),
  ('Fonacot [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Fonacot', 'Polo', true, true),
  ('Fonacot [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Fonacot', 'Eventos', true, true),
  ('Fonacot [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Fonacot', 'Patron''s', true, true),
  ('Finiquitos y Liquidaciones [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Finiquitos y Liquidaciones', 'Golf', true, true),
  ('Finiquitos y Liquidaciones [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Finiquitos y Liquidaciones', 'Mantenimiento', true, true),
  ('Finiquitos y Liquidaciones [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Finiquitos y Liquidaciones', 'Hípico', true, true),
  ('Finiquitos y Liquidaciones [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Finiquitos y Liquidaciones', 'Polo', true, true),
  ('Finiquitos y Liquidaciones [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Finiquitos y Liquidaciones', 'Eventos', true, true),
  ('Finiquitos y Liquidaciones [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Finiquitos y Liquidaciones', 'Patron''s', true, true),
  ('Vales Despensa [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Vales Despensa', 'Golf', true, true),
  ('Vales Despensa [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Vales Despensa', 'Mantenimiento', true, true),
  ('Vales Despensa [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Vales Despensa', 'Hípico', true, true),
  ('Vales Despensa [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Vales Despensa', 'Polo', true, true),
  ('Vales Despensa [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Vales Despensa', 'Eventos', true, true),
  ('Vales Despensa [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Vales Despensa', 'Patron''s', true, true),
  ('Capacitación [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Capacitación', 'Golf', true, true),
  ('Capacitación [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Capacitación', 'Mantenimiento', true, true),
  ('Capacitación [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Capacitación', 'Hípico', true, true),
  ('Capacitación [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Capacitación', 'Polo', true, true),
  ('Capacitación [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Capacitación', 'Eventos', true, true),
  ('Capacitación [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Capacitación', 'Patron''s', true, true),
  ('Impuestos, Derechos y Aprovech. municipales [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Impuestos, Derechos y Aprovech. municipales', 'Golf', true, true),
  ('Impuestos, Derechos y Aprovech. municipales [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Impuestos, Derechos y Aprovech. municipales', 'Mantenimiento', true, true),
  ('Impuestos, Derechos y Aprovech. municipales [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Impuestos, Derechos y Aprovech. municipales', 'Hípico', true, true),
  ('Impuestos, Derechos y Aprovech. municipales [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Impuestos, Derechos y Aprovech. municipales', 'Polo', true, true),
  ('Impuestos, Derechos y Aprovech. municipales [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Impuestos, Derechos y Aprovech. municipales', 'Eventos', true, true),
  ('Impuestos, Derechos y Aprovech. municipales [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Impuestos, Derechos y Aprovech. municipales', 'Patron''s', true, true),
  ('Recolección de Basura [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Recolección de Basura', 'Golf', true, true),
  ('Recolección de Basura [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Recolección de Basura', 'Mantenimiento', true, true),
  ('Recolección de Basura [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Recolección de Basura', 'Hípico', true, true),
  ('Recolección de Basura [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Recolección de Basura', 'Polo', true, true),
  ('Recolección de Basura [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Recolección de Basura', 'Eventos', true, true),
  ('Recolección de Basura [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Recolección de Basura', 'Patron''s', true, true),
  ('Servicios de IT [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Servicios de IT', 'Golf', true, true),
  ('Servicios de IT [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Servicios de IT', 'Mantenimiento', true, true),
  ('Servicios de IT [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Servicios de IT', 'Hípico', true, true),
  ('Servicios de IT [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Servicios de IT', 'Polo', true, true),
  ('Servicios de IT [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Servicios de IT', 'Eventos', true, true),
  ('Servicios de IT [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Servicios de IT', 'Patron''s', true, true),
  ('Licencias de Software [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Licencias de Software', 'Golf', true, true),
  ('Licencias de Software [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Licencias de Software', 'Mantenimiento', true, true),
  ('Licencias de Software [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Licencias de Software', 'Hípico', true, true),
  ('Licencias de Software [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Licencias de Software', 'Polo', true, true),
  ('Licencias de Software [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Licencias de Software', 'Eventos', true, true),
  ('Licencias de Software [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Licencias de Software', 'Patron''s', true, true),
  ('Equipo de Computo y Tecnología [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Equipo de Computo y Tecnología', 'Golf', true, true),
  ('Equipo de Computo y Tecnología [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Equipo de Computo y Tecnología', 'Mantenimiento', true, true),
  ('Equipo de Computo y Tecnología [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Equipo de Computo y Tecnología', 'Hípico', true, true),
  ('Equipo de Computo y Tecnología [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Equipo de Computo y Tecnología', 'Polo', true, true),
  ('Equipo de Computo y Tecnología [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Equipo de Computo y Tecnología', 'Eventos', true, true),
  ('Equipo de Computo y Tecnología [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Equipo de Computo y Tecnología', 'Patron''s', true, true),
  ('Compra Maquinaria y Equipo [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Compra Maquinaria y Equipo', 'Golf', true, true),
  ('Compra Maquinaria y Equipo [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Compra Maquinaria y Equipo', 'Mantenimiento', true, true),
  ('Compra Maquinaria y Equipo [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Compra Maquinaria y Equipo', 'Hípico', true, true),
  ('Compra Maquinaria y Equipo [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Compra Maquinaria y Equipo', 'Polo', true, true),
  ('Compra Maquinaria y Equipo [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Compra Maquinaria y Equipo', 'Eventos', true, true),
  ('Compra Maquinaria y Equipo [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Compra Maquinaria y Equipo', 'Patron''s', true, true),
  ('Agua en Garrafón [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Agua en Garrafón', 'Golf', true, true),
  ('Agua en Garrafón [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Agua en Garrafón', 'Mantenimiento', true, true),
  ('Agua en Garrafón [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Agua en Garrafón', 'Hípico', true, true),
  ('Agua en Garrafón [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Agua en Garrafón', 'Polo', true, true),
  ('Agua en Garrafón [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Agua en Garrafón', 'Eventos', true, true),
  ('Agua en Garrafón [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Agua en Garrafón', 'Patron''s', true, true),
  ('Gas LP [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Gas LP', 'Golf', true, true),
  ('Gas LP [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Gas LP', 'Mantenimiento', true, true),
  ('Gas LP [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Gas LP', 'Hípico', true, true),
  ('Gas LP [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Gas LP', 'Polo', true, true),
  ('Gas LP [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Gas LP', 'Eventos', true, true),
  ('Gas LP [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Gas LP', 'Patron''s', true, true),
  ('Pipas de Agua [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Pipas de Agua', 'Golf', true, true),
  ('Pipas de Agua [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Pipas de Agua', 'Mantenimiento', true, true),
  ('Pipas de Agua [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Pipas de Agua', 'Hípico', true, true),
  ('Pipas de Agua [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Pipas de Agua', 'Polo', true, true),
  ('Pipas de Agua [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Pipas de Agua', 'Eventos', true, true),
  ('Pipas de Agua [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Pipas de Agua', 'Patron''s', true, true),
  ('Medicamento y Botiquin [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Medicamento y Botiquin', 'Golf', true, true),
  ('Medicamento y Botiquin [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Medicamento y Botiquin', 'Mantenimiento', true, true),
  ('Medicamento y Botiquin [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Medicamento y Botiquin', 'Hípico', true, true),
  ('Medicamento y Botiquin [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Medicamento y Botiquin', 'Polo', true, true),
  ('Medicamento y Botiquin [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Medicamento y Botiquin', 'Eventos', true, true),
  ('Medicamento y Botiquin [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Medicamento y Botiquin', 'Patron''s', true, true),
  ('Servicios de Paramédicos [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Servicios de Paramédicos', 'Golf', true, true),
  ('Servicios de Paramédicos [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Servicios de Paramédicos', 'Mantenimiento', true, true),
  ('Servicios de Paramédicos [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Servicios de Paramédicos', 'Hípico', true, true),
  ('Servicios de Paramédicos [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Servicios de Paramédicos', 'Polo', true, true),
  ('Servicios de Paramédicos [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Servicios de Paramédicos', 'Eventos', true, true),
  ('Servicios de Paramédicos [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Servicios de Paramédicos', 'Patron''s', true, true),
  ('Comisiones por Ventas/Cobranza [Operación Golf] [Golf]', 'egreso', 2, 39, 6, true, 'op_area', 'Comisiones por Ventas/Cobranza', 'Golf', true, true),
  ('Comisiones por Ventas/Cobranza [Operación Mantto. Res.] [Mantenimiento]', 'egreso', 1, 21, 6, true, 'op_area', 'Comisiones por Ventas/Cobranza', 'Mantenimiento', true, true),
  ('Comisiones por Ventas/Cobranza [Operación Hípico] [Hípico]', 'egreso', 3, 40, 6, true, 'op_area', 'Comisiones por Ventas/Cobranza', 'Hípico', true, true),
  ('Comisiones por Ventas/Cobranza [Operación Polo] [Polo]', 'egreso', 4, 41, 6, true, 'op_area', 'Comisiones por Ventas/Cobranza', 'Polo', true, true),
  ('Comisiones por Ventas/Cobranza [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Comisiones por Ventas/Cobranza', 'Eventos', true, true),
  ('Comisiones por Ventas/Cobranza [Operación Patron''s] [Patron''s]', 'egreso', 5, 42, 6, true, 'op_area', 'Comisiones por Ventas/Cobranza', 'Patron''s', true, true),
  ('Alimento para Caballos [Caballerizas] [Hípico]', 'egreso', 3, 25, 6, true, 'op_area', 'Alimento para Caballos', 'Hípico', true, true),
  ('Medicamentos e Insumos Veterinarios [Caballerizas] [Hípico]', 'egreso', 3, 25, 6, true, 'op_area', 'Medicamentos e Insumos Veterinarios', 'Hípico', true, true),
  ('Catering [Operación Eventos] [Eventos]', 'egreso', 7, 45, 6, true, 'op_area', 'Catering', 'Eventos', true, true);

COMMIT;
