-- Formaliza TODAS las categorías de gasto real (área + tipo_gasto) que aún no
-- tenían partida específica, para dejar de inflar "Otros Gastos [Área]" con
-- gasto que sí es categorizable. Se excluyen a propósito las combinaciones con
-- tipo_gasto='Otro' (genéricas desde el origen, no hay categoría más específica
-- que asignarles) y las OP con OC (tipo_gasto=null) — ambas siguen cayendo,
-- correctamente, en el catch-all "Otros Gastos [Área]" de cada área.
--
-- 77 partidas nuevas, auditoría 2026-08-14 (ver memoria
-- project_ppto_categorias_sin_partida_masivo).

BEGIN;

INSERT INTO ctrl.ppto_partidas
  (nombre, tipo, id_centro_costo_fk, id_area_fk, orden, activo, fuente_real, tipo_gasto, modulo, incluir_presupuesto, incluir_flujo)
VALUES
  ('Nómina Semanal [Operaciones Hospitality]', 'egreso', 7, 45, 2, true, 'op_area', 'Nómina Semanal', 'Eventos', true, true),
  ('Reparación [/revisar)]', 'egreso', 2, 34, 2, true, 'op_area', 'Reparación', 'Golf', true, true),
  ('Agua [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Agua', 'Golf', true, true),
  ('Arrendamiento [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Arrendamiento', 'Golf', true, true),
  ('Combustible [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Combustible', 'Golf', true, true),
  ('Honorarios [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Honorarios', 'Golf', true, true),
  ('Mantenimiento [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Mantenimiento', 'Golf', true, true),
  ('Publicidad [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Publicidad', 'Golf', true, true),
  ('Reparación [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Reparación', 'Golf', true, true),
  ('Servicios Profesionales [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Servicios Profesionales', 'Golf', true, true),
  ('Telefonía / Internet [Admón. Golf]', 'egreso', 2, 39, 2, true, 'op_area', 'Telefonía / Internet', 'Golf', true, true),
  ('Agua [Campo de Golf]', 'egreso', 2, 23, 2, true, 'op_area', 'Agua', 'Golf', true, true),
  ('Asesoría [Campo de Golf]', 'egreso', 2, 23, 2, true, 'op_area', 'Asesoría', 'Golf', true, true),
  ('Combustible [Campo de Golf]', 'egreso', 2, 23, 2, true, 'op_area', 'Combustible', 'Golf', true, true),
  ('Electricidad [Campo de Golf]', 'egreso', 2, 23, 2, true, 'op_area', 'Electricidad', 'Golf', true, true),
  ('Mantenimiento [Campo de Golf]', 'egreso', 2, 23, 2, true, 'op_area', 'Mantenimiento', 'Golf', true, true),
  ('Servicios Profesionales [Campo de Golf]', 'egreso', 2, 23, 2, true, 'op_area', 'Servicios Profesionales', 'Golf', true, true),
  ('Electricidad [Casa Club]', 'egreso', 2, 24, 2, true, 'op_area', 'Electricidad', 'Golf', true, true),
  ('Mantenimiento [Casa Club]', 'egreso', 2, 24, 2, true, 'op_area', 'Mantenimiento', 'Golf', true, true),
  ('Reparación [Casa Club]', 'egreso', 2, 24, 2, true, 'op_area', 'Reparación', 'Golf', true, true),
  ('Servicios Profesionales [Casa Club]', 'egreso', 2, 24, 2, true, 'op_area', 'Servicios Profesionales', 'Golf', true, true),
  ('Electricidad [Tee de Practica]', 'egreso', 2, 44, 2, true, 'op_area', 'Electricidad', 'Golf', true, true),
  ('Combustible [Admón. Hípico]', 'egreso', 3, 40, 2, true, 'op_area', 'Combustible', 'Hípico', true, true),
  ('Electricidad [Admón. Hípico]', 'egreso', 3, 40, 2, true, 'op_area', 'Electricidad', 'Hípico', true, true),
  ('Honorarios [Admón. Hípico]', 'egreso', 3, 40, 2, true, 'op_area', 'Honorarios', 'Hípico', true, true),
  ('Combustible [Caballerizas]', 'egreso', 3, 25, 2, true, 'op_area', 'Combustible', 'Hípico', true, true),
  ('Electricidad [Caballerizas]', 'egreso', 3, 25, 2, true, 'op_area', 'Electricidad', 'Hípico', true, true),
  ('Mantenimiento [Caballerizas]', 'egreso', 3, 25, 2, true, 'op_area', 'Mantenimiento', 'Hípico', true, true),
  ('Reparación [Caballerizas]', 'egreso', 3, 25, 2, true, 'op_area', 'Reparación', 'Hípico', true, true),
  ('Agua [Paddocks]', 'egreso', 3, 29, 2, true, 'op_area', 'Agua', 'Hípico', true, true),
  ('Combustible [Paddocks]', 'egreso', 3, 29, 2, true, 'op_area', 'Combustible', 'Hípico', true, true),
  ('Electricidad [Paddocks]', 'egreso', 3, 29, 2, true, 'op_area', 'Electricidad', 'Hípico', true, true),
  ('Agua [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Agua', 'Mantenimiento', true, true),
  ('Arrendamiento [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Arrendamiento', 'Mantenimiento', true, true),
  ('Combustible [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Combustible', 'Mantenimiento', true, true),
  ('Electricidad [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Electricidad', 'Mantenimiento', true, true),
  ('Honorarios [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Honorarios', 'Mantenimiento', true, true),
  ('Impuestos Estatales [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Impuestos Estatales', 'Mantenimiento', true, true),
  ('Mantenimiento [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Mantenimiento', 'Mantenimiento', true, true),
  ('Renta de Mobiliario [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Renta de Mobiliario', 'Mantenimiento', true, true),
  ('Reparación [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Reparación', 'Mantenimiento', true, true),
  ('Servicios Profesionales [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Servicios Profesionales', 'Mantenimiento', true, true),
  ('Telefonía / Internet [Admón. Mantto Residencial]', 'egreso', 1, 21, 2, true, 'op_area', 'Telefonía / Internet', 'Mantenimiento', true, true),
  ('Agua [Mantto. Agaves]', 'egreso', 1, 1, 2, true, 'op_area', 'Agua', 'Mantenimiento', true, true),
  ('Mantenimiento [Mantto. Agaves]', 'egreso', 1, 1, 2, true, 'op_area', 'Mantenimiento', 'Mantenimiento', true, true),
  ('Servicios Profesionales [Mantto. Agaves]', 'egreso', 1, 1, 2, true, 'op_area', 'Servicios Profesionales', 'Mantenimiento', true, true),
  ('Arrendamiento [Mantto. Circuito Balvanera]', 'egreso', 1, 22, 2, true, 'op_area', 'Arrendamiento', 'Mantenimiento', true, true),
  ('Electricidad [Mantto. Circuito Balvanera]', 'egreso', 1, 22, 2, true, 'op_area', 'Electricidad', 'Mantenimiento', true, true),
  ('Mantenimiento [Mantto. Circuito Balvanera]', 'egreso', 1, 22, 2, true, 'op_area', 'Mantenimiento', 'Mantenimiento', true, true),
  ('Servicios Profesionales [Mantto. Circuito Balvanera]', 'egreso', 1, 22, 2, true, 'op_area', 'Servicios Profesionales', 'Mantenimiento', true, true),
  ('Reparación [Mantto. Cordillera II]', 'egreso', 1, 15, 2, true, 'op_area', 'Reparación', 'Mantenimiento', true, true),
  ('Mantenimiento [Mantto. Fairway VIP]', 'egreso', 1, 16, 2, true, 'op_area', 'Mantenimiento', 'Mantenimiento', true, true),
  ('Electricidad [Mantto. Fundadores]', 'egreso', 1, 11, 2, true, 'op_area', 'Electricidad', 'Mantenimiento', true, true),
  ('Electricidad [Mantto. Palermo Balvanera]', 'egreso', 1, 5, 2, true, 'op_area', 'Electricidad', 'Mantenimiento', true, true),
  ('Mantenimiento [Mantto. Palermo Balvanera]', 'egreso', 1, 5, 2, true, 'op_area', 'Mantenimiento', 'Mantenimiento', true, true),
  ('Servicios Profesionales [Mantto. Palermo Balvanera]', 'egreso', 1, 5, 2, true, 'op_area', 'Servicios Profesionales', 'Mantenimiento', true, true),
  ('Mantenimiento [Mantto. Panorámica]', 'egreso', 1, 2, 2, true, 'op_area', 'Mantenimiento', 'Mantenimiento', true, true),
  ('Agua [Mantto. Privada Palermo]', 'egreso', 1, 7, 2, true, 'op_area', 'Agua', 'Mantenimiento', true, true),
  ('Electricidad [Mantto. South Hill]', 'egreso', 1, 9, 2, true, 'op_area', 'Electricidad', 'Mantenimiento', true, true),
  ('Mantenimiento [Mantto. South Hill]', 'egreso', 1, 9, 2, true, 'op_area', 'Mantenimiento', 'Mantenimiento', true, true),
  ('Servicios Profesionales [Mantto. South Hill]', 'egreso', 1, 9, 2, true, 'op_area', 'Servicios Profesionales', 'Mantenimiento', true, true),
  ('Electricidad [Mantto. South Hill Fairway]', 'egreso', 1, 51, 2, true, 'op_area', 'Electricidad', 'Mantenimiento', true, true),
  ('Arrendamiento [Vigilancia]', 'egreso', 1, 36, 2, true, 'op_area', 'Arrendamiento', 'Mantenimiento', true, true),
  ('Combustible [Vigilancia]', 'egreso', 1, 36, 2, true, 'op_area', 'Combustible', 'Mantenimiento', true, true),
  ('Reparación [Vigilancia]', 'egreso', 1, 36, 2, true, 'op_area', 'Reparación', 'Mantenimiento', true, true),
  ('Servicios de Vigilancia [Vigilancia]', 'egreso', 1, 36, 2, true, 'op_area', 'Servicios de Vigilancia', 'Mantenimiento', true, true),
  ('Telefonía / Internet [Vigilancia]', 'egreso', 1, 36, 2, true, 'op_area', 'Telefonía / Internet', 'Mantenimiento', true, true),
  ('Electricidad [Admón. Patron''s]', 'egreso', 5, 42, 2, true, 'op_area', 'Electricidad', 'Patron''s', true, true),
  ('Nómina Semanal [Admón. Patron''s]', 'egreso', 5, 42, 2, true, 'op_area', 'Nómina Semanal', 'Patron''s', true, true),
  ('Reparación [Admón. Patron''s]', 'egreso', 5, 42, 2, true, 'op_area', 'Reparación', 'Patron''s', true, true),
  ('Electricidad [Casa Azul]', 'egreso', 5, 33, 2, true, 'op_area', 'Electricidad', 'Patron''s', true, true),
  ('Mantenimiento [Casa Azul]', 'egreso', 5, 33, 2, true, 'op_area', 'Mantenimiento', 'Patron''s', true, true),
  ('Electricidad [Casa Patron''s]', 'egreso', 5, 50, 2, true, 'op_area', 'Electricidad', 'Patron''s', true, true),
  ('Nómina Semanal [Casa Patron''s]', 'egreso', 5, 50, 2, true, 'op_area', 'Nómina Semanal', 'Patron''s', true, true),
  ('Honorarios [Admon. Polo]', 'egreso', 4, 41, 2, true, 'op_area', 'Honorarios', 'Polo', true, true),
  ('Reparación [Admon. Polo]', 'egreso', 4, 41, 2, true, 'op_area', 'Reparación', 'Polo', true, true),
  ('Servicios Profesionales [Admon. Polo]', 'egreso', 4, 41, 2, true, 'op_area', 'Servicios Profesionales', 'Polo', true, true);

COMMIT;
